/* eslint-disable no-restricted-globals */
// src/service-worker.js

import { precacheAndRoute } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { StaleWhileRevalidate } from "workbox-strategies";

// Precache all the assets generated by the build process.
precacheAndRoute(self.__WB_MANIFEST);

// Cache CSS and JS files
registerRoute(
  ({ request }) =>
    request.destination === "style" || request.destination === "script",
  new StaleWhileRevalidate()
);

// Cache images
registerRoute(
  ({ request }) => request.destination === "image",
  new StaleWhileRevalidate()
);
